import tseslint from 'typescript-eslint';

export default [
  {
    ignores: [
      'extension/**',
      'outputs/**',
      'work/discourse-boosts/**',
      'work/main.test.mjs',
    ],
  },
  {
    name: 'linuxdo-userscript',
    files: ['work/main.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        AbortController: 'readonly',
        CustomEvent: 'readonly',
        DOMException: 'readonly',
        Element: 'readonly',
        FormData: 'readonly',
        IDBKeyRange: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        Node: 'readonly',
        NodeFilter: 'readonly',
        ResizeObserver: 'readonly',
        Response: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        alert: 'readonly',
        caches: 'readonly',
        cancelAnimationFrame: 'readonly',
        cancelIdleCallback: 'readonly',
        chrome: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        document: 'readonly',
        fetch: 'readonly',
        getComputedStyle: 'readonly',
        history: 'readonly',
        indexedDB: 'readonly',
        localStorage: 'readonly',
        location: 'readonly',
        matchMedia: 'readonly',
        navigator: 'readonly',
        performance: 'readonly',
        queueMicrotask: 'readonly',
        requestAnimationFrame: 'readonly',
        requestIdleCallback: 'readonly',
        sessionStorage: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        window: 'readonly',
      },
    },
    rules: {
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-undef': 'warn',
      'no-unreachable': 'error',
      'valid-typeof': 'error',
    },
  },
  {
    name: 'userscript-build-tool',
    files: [
      'eslint.config.mjs',
      'scripts/audit-main-runtime.mjs',
      'scripts/build-mian-lite.mjs',
      'scripts/build-userscript.mjs',
      'scripts/test-mian-lite.mjs',
      'docs/.vitepress/config.mts',
    ],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        Buffer: 'readonly',
        process: 'readonly',
        URL: 'readonly',
      },
    },
    rules: {
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-undef': 'error',
      'no-unreachable': 'error',
      'valid-typeof': 'error',
    },
  },
  {
    name: 'mian-lite-typescript',
    files: ['lite/src/**/*.ts', 'lite/tests/**/*.ts'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    rules: {
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-undef': 'off',
      'no-unreachable': 'error',
      'valid-typeof': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
    },
  },
];
